### PR TITLE
Start Preview and Daily builds on Focal

### PR DESCRIPTION
**Pull request by AndrewMcClain**
Goals Here:
Build an Ubuntu 2004 Focal base image
Switch our preview and daily builds to focal
Still have to maintain 1804 Bionic until 2023.05 released, so latest still produces bionic builds as of now.

On 2023.05's release, we'll update this again to pull the remaining latest build onto focal.

### CODE REVIEW

**Comment by cm421** [comment]
To get the `product-base-pro` focal images in place, should the `product/base/Dockerfile.ubuntu2004` dockerfile be in its own PR? Once that's in, then these automated checks should pass

**Comment by colearendt** [comment]
Wait, why are we switching to Focal? We are already building Jammy images?

**Comment by colearendt** [comment]
> This mirrors the bionic/jammy distinction we had previously.

I personally don't think it's worth the effort. The reason we are maintaining both `bionic` and `jammy` right now is b/c `bionic` is EOL.  We "skipped" focal, so I'd save the development effort for a discussion about whether to support RHEL 8 or RHEL 9 images (#305), and perhaps another ubuntu LTS line next year (24.04). 

If we choose to maintain an image, we should do it for some customer value / reason. At present, focal has the smallest potential upside of any new OS choice IMO. Happy to be persuaded otherwise, but I'd suggest we focus effort elsewhere and make such OS choices carefully / platform wide (since it forks our entire development line). We also have latent demand for ARM images too.

**Comment by AndrewMcClain** [comment]
After Discussion with Maria, Cole and Zach, the introduction of focal images is unnecessary, so I'm closing this PR as won't merge. I'll open a new PR with the changes to just stop building Bionic images.

**Pull request closed without merging**
