### PR TITLE
Bump Connect to version 2023.10.0

### PR DESCRIPTION
**Pull request by dethmasque**
This PR was created automatically by the Posit Connect release scripts.

### CODE REVIEW

**Comment by ianpittwood** [comment]
@dethmasque FYI this missed some version bumps. I'll do them myself and merge your PR though, we have several critical changes that need to get into main already.

**Comment by aronatkins** [comment]
@ianpittwood - What is missing? Our tooling sets `RSC_VERSION` and runs `update-rsc-versions`, submitting a PR against both `main` and `dev`.

CC @dbkegley

**Comment by ianpittwood** [comment]
@aronatkins please disregard, I was looking at the branch locally and for some reason it wasn't pulling the connect-content-init changes.

**Review by ianpittwood — APPROVED** [review]

**Comment by ianpittwood** [comment]
I'll shepherd this change through to `main` release once CI passes.

**Pull request merged**
