### PR TITLE
Update Package Manager to v2022.11.0-13

### PR DESCRIPTION
**Pull request by jonyoder**

### CODE REVIEW

**Comment by ianpittwood** [comment]
@jonyoder somehow half of a regex string in the alt Python versions update got dropped... I'll fix it.

**Comment by jonyoder** [comment]
@ianpittwood thanks! Let me know if I need to rebase or fix anything here.

**Comment by ianpittwood** [comment]
Fixed in #429

**Comment by jonyoder** [comment]
All done. This should be ready for a review now, but please wait to merge until tomorrow since we haven't fully released 2022.11 yet.

**Review by ianpittwood — APPROVED** [review]
LGTM!

**Review by shepherdjerred — APPROVED** [review]

**Comment by jonyoder** [comment]
Is this ok to merge, or do the tests all need to pass?

**Comment by colearendt** [comment]
AOK to merge 😄 The RSW daily / preview images are broken until their next release 😅

**Pull request merged**
