### PR TITLE
RStudio Connect release 2022.02.2

### PR DESCRIPTION
**Pull request by marcosnav**
Bump Connect version to 2022.02.2

### CODE REVIEW

**Review by dethmasque — APPROVED** [review]
LGTM! 🦜🦭🐠

**Comment by colearendt** [comment]
@marcosnav do you mind signing the CLA? 😄 It's a little silly, but it makes CI happy haha

**Comment by marcosnav** [comment]
@colearendt sure! done 🙂

**Review by colearendt — APPROVED** [review]
Nice, thanks! Feel free to merge at will!

**Review by aronatkins — APPROVED** [review]

**Pull request merged**
