### PR TITLE
Update umask from 0027 to 0077 per security recommendation

### PR DESCRIPTION
**Pull request by zachhannum**
Per security's recommendation, we want to also disallow group access in user home directories by default.

### CODE REVIEW

**Review by jeffvroom — APPROVED** [review]
LGTM!  Is there a way we can alert customers about this change to behavior, like a release note or something?

**Review by melissa-barca — APPROVED** [review]
LGTM!

**Review by ianpittwood — CHANGES_REQUESTED** [review]
@zachhannum could  you add something in the `workbench/NEWS.md` for this?

**Comment by zachhannum** [comment]
> @zachhannum could you add something in the `workbench/NEWS.md` for this?

Done!

**Comment by aja08379** [comment]
@ianpittwood can we get this merged? Cheers!

**Review by ianpittwood — APPROVED** [review]

**Pull request merged**
