### PR TITLE
update daily workbench branch

### PR DESCRIPTION
**Pull request by melissa-barca**
Update release used for daily builds to ocean storm

### CODE REVIEW

**Review by bschwedler — APPROVED** [review]
LGTM

**Comment by bschwedler** [comment]
@ianpittwood did we want to get this merged into `dev` first? 

I approved so I wouldn't be a blocker.

**Comment by ianpittwood** [comment]
@bschwedler yeah thanks, let's move this into `dev` first. That's what dailies will begin building off of.

**Comment by melissa-barca** [comment]
Thanks for the assist @bschwedler!

**Pull request merged**
