### PR TITLE
Expand on CODEOWNERS file

### PR DESCRIPTION
**Pull request by ianpittwood**
Added ownership assignments for Connect and Workbench.

### CODE REVIEW

**Comment by ianpittwood** [comment]
@colearendt I saw you already added the file so I just expanded on it. My main goal is to close #306 so just let me know if you think the version in main is good as is and I can close both this PR and the issue.

**Comment by colearendt** [comment]
Howdy @ianpittwood ! This looks great - I think I would probably consider #306 closed FWIW (I just forgot to close it when I merged the previous PR).

The only hesitation I have here is that it will be pretty noisy and potentially disruptive to the RSC / IDE teams, and they have not been briefed on / agreed to be party to all of the PRs in this repo 😅 As such, I would definitely hold this PR open, but it's probably worth sanity checking that this number of notifications is acceptable to the teams. (The RSPM team specifically agreed to be a CODE_OWNER).

**Comment by kfeinauer** [comment]
@ianpittwood @colearendt Agree this could be spammy. I think we should reach out to the teams to see who wants to be included here.

@MariaSemple 
@aronatkins 

Could you two comment on who should be added to the CODEOWNERS file for the RSW and RSC Docker images?

**Comment by MariaSemple** [comment]
I've put this on the agenda to be discussed at our next team meeting, and will update here with the result of the discussion.

**Review by aronatkins — APPROVED** [review]
The `@rstudio/connect` team may eventually prove to be too broad, but is probably the best option we have available. Let's start with this and adjust later.

**Comment by ianpittwood** [comment]
@MariaSemple did your team discuss yet?

**Comment by MariaSemple** [comment]
Not yet - next Thursday.

**Comment by MariaSemple** [comment]
For the Workbench team, could you set @melissa-barca and @cm421 as our code-owners?

**Comment by ianpittwood** [comment]
Thanks, @MariaSemple! Everything should be updated and ready for review @atheriel @colearendt!

**Review by MariaSemple — APPROVED** [review]
LGTM!

**Review by colearendt — APPROVED** [review]
LGTM! The only additional thought I had is maybe to add the RSW team to the `r-session-complete` images?

**Comment by ianpittwood** [comment]
@MariaSemple thoughts?

**Comment by ianpittwood** [comment]
Maria approved of adding the same owners for workbench to r-session-complete. I updated the CODEOWNERS file and will merge once checks finish.

**Pull request merged**
