### PR TITLE
Bump PWB to 2023.12.1+402.pro1

### PR DESCRIPTION
**Pull request by GCRev**

### CODE REVIEW

**Review by melissa-barca — APPROVED** [review]
LGTM

**Comment by GCRev** [comment]
We can merge this but 2 (3?) of the checks failed.
One wasn't happy about `launcher.pem`'s read-write permissions
The other seemed like it ran out of drive space when building the image.

Do we want to consider those to be non-issues?

**Comment by GCRev** [comment]
@ianpittwood could you assess whether we should merge based on the failures from the check runs?

**Comment by ianpittwood** [comment]
@GCRev As you probably saw, I pushed a "fix" (removing R 3.6.3) for the Workbench AML definition so it stops erroring out. I need to do some testing locally for Workbench GCW to figure out why that's failing. Once that's done I think we should be good though. The daily build failure looked related to whatever Workbench build was used so I'm not concerned with that for now.

**Comment by ianpittwood** [comment]
@GCRev We're good to go here. The GCW issue seems like a one-off.

**Comment by GCRev** [comment]
Thank you!

**Pull request merged**
