### PR TITLE
Remove VS Code install step and correct code-server path

### PR DESCRIPTION
**Pull request by ianpittwood**

### CODE REVIEW

**Review by MariaSemple — APPROVED** [review]
LGTM!

**Review by colearendt — APPROVED** [review]
LGTM!

**Comment by colearendt** [comment]
Really strange that CI is still failing... 
```
2022-10-18T21:27:04.203633Z [rserver] ERROR system error 13 (Permission denied) [description: The config file /etc/rstudio/launcher.pem must have user read/write permissions (to protect its contents). Please change its permissions to user read/write as follows: sudo chmod 0600 /etc/rstudio/launcher.pem]; OCCURRED AT rstudio::core::Error rstudio::server::job_launcher::{anonymous}::loadLauncherKeys() src/cpp/server/ServerJobLauncher.cpp:266; LOGGED FROM: int main(int, char* const*) src/cpp/server/ServerMain.cpp:833
```

**Comment by ianpittwood** [comment]
> Really strange that CI is still failing... I thought this file was auto-generated by Workbench...
> 
> ```
> 
> 2022-10-18T21:27:04.203633Z [rserver] ERROR system error 13 (Permission denied) [description: The config file /etc/rstudio/launcher.pem must have user read/write permissions (to protect its contents). Please change its permissions to user read/write as follows: sudo chmod 0600 /etc/rstudio/launcher.pem]; OCCURRED AT rstudio::core::Error rstudio::server::job_launcher::{anonymous}::loadLauncherKeys() src/cpp/server/ServerJobLauncher.cpp:266; LOGGED FROM: int main(int, char* const*) src/cpp/server/ServerMain.cpp:833
> 
> ```

Yeah I saw that we had some failures still. I'll take a look tomorrow to see what's up.

**Comment by ianpittwood** [comment]
@colearendt the remaining errors seem expected, but can you double check before I merge?

**Pull request merged**
