### PR TITLE
Add update-drivers command to Makefile

### PR DESCRIPTION
**Pull request by ianpittwood**
Adds the command, `update-drivers`, to update the drivers' version per #190.

The command updates the following files:

- content/pro/Makefile:19
- content/matrix.json
- helper/workbench-for-microsoft-azure-ml/Dockerfile

### CODE REVIEW

**Comment by zfouts** [comment]
lgtm, please rebase to main and get a successful Azure build and I'll approve

**Comment by ianpittwood** [comment]
@zfouts should be good now.

**Review by zfouts — APPROVED** [review]
lgtm 🚢

**Review by colearendt — APPROVED** [review]
Nice!

**Pull request merged**
