### PR TITLE
Update Package Manager's Python version

### PR DESCRIPTION
**Pull request by shepherdjerred**
https://github.com/rstudio/package-manager/issues/12544

### CODE REVIEW

**Review by jonyoder — APPROVED** [review]
I'm ok with this, but I'd feel better if someone on the platform team would also take a look.

**Review by jmwoliver — APPROVED** [review]

**Review by ianpittwood — CHANGES_REQUESTED** [review]
All good with updating this, but you'll have to change a few more spots to get the new versions in image builds:
- Add a new base image that builds with these Python versions in here: 
  - https://github.com/rstudio/rstudio-docker-products/blob/dev/.github/workflows/build-release.yaml#L28-L32
  - https://github.com/rstudio/rstudio-docker-products/blob/dev/.github/workflows/build-release.yaml#L136-L140 (not explicitly required for PPM's use, but let's add it anyways :grin:)
- Update the Python versions used for the release build here: https://github.com/rstudio/rstudio-docker-products/blob/dev/.github/workflows/build-release.yaml#L251
- Update the Python versions used for dailies and prereleases here: https://github.com/rstudio/rstudio-docker-products/blob/dev/.github/workflows/build-prerelease.yaml#L33
- Update the defaults in the Dockerfile: https://github.com/rstudio/rstudio-docker-products/blob/dev/package-manager/Dockerfile.ubuntu2204#L3-L4
- Update the NEWS.md for PPM with the change: https://github.com/rstudio/rstudio-docker-products/blob/dev/package-manager/NEWS.md

Sorry it's a bit of a clunky process. The `Justfile` shortcuts we currently have were only meant for updating *all* the Python/R versions across all products. Refactoring this repo is next on my list after Marketplaces.

**Comment by shepherdjerred** [comment]
> All good with updating this, but you'll have to change a few more spots to get the new versions in image builds:
> 
> * Add a new base image that builds with these Python versions in here:
>   
>   * https://github.com/rstudio/rstudio-docker-products/blob/dev/.github/workflows/build-release.yaml#L28-L32
>   * https://github.com/rstudio/rstudio-docker-products/blob/dev/.github/workflows/build-release.yaml#L136-L140 (not explicitly required for PPM's use, but let's add it anyways 😁)
> * Update the Python versions used for the release build here: https://github.com/rstudio/rstudio-docker-products/blob/dev/.github/workflows/build-release.yaml#L251
> * Update the Python versions used for dailies and prereleases here: https://github.com/rstudio/rstudio-docker-products/blob/dev/.github/workflows/build-prerelease.yaml#L33
> * Update the defaults in the Dockerfile: https://github.com/rstudio/rstudio-docker-products/blob/dev/package-manager/Dockerfile.ubuntu2204#L3-L4
> * Update the NEWS.md for PPM with the change: https://github.com/rstudio/rstudio-docker-products/blob/dev/package-manager/NEWS.md
> 
> Sorry it's a bit of a clunky process. The `Justfile` shortcuts we currently have were only meant for updating _all_ the Python/R versions across all products. Refactoring this repo is next on my list after Marketplaces.

Thanks for this great feedback Ian. I believe I've done everything you've pointed out. Going to wait for CI to pass!

**Comment by shepherdjerred** [comment]
@ianpittwood It looks like it's failing to find the newly created base Docker image. This is expected, right, since the Docker image wouldn't be created until this PR is merged in?

**Comment by ianpittwood** [comment]
> @ianpittwood It looks like it's failing to find the newly created base Docker image. This is expected, right, since the Docker image wouldn't be created until this PR is merged in?

Yes, it should work as soon as it's merged! I've got a ticket out there to fix that behavior when updating base builds.

**Review by ianpittwood — APPROVED** [review]

**Pull request merged**
