### PR TITLE
DONT MERGE overall updates

### PR DESCRIPTION
**Pull request by slopp**
updated R
updated Python
added drivers

probably shouldn't merge this till we decide if we want to swap out R/Py versions or append them

### CODE REVIEW

**Comment by slopp** [comment]
yikes! we also need a way to have the py version flow through to the .gcfg file ....

**Comment by colearendt** [comment]
Yeah I have been debating this update, because anyone blindly using this image will immediately get broken content the next time they pull. I thought about coinciding it with an upgrade to the product version so that it would be a part of the upgrade process (but I keep forgetting to do that)... and I also punted on waiting until we have different runtimes available via the launcher 🤷‍♂️  The upgrade story is a tricky one

**Comment by colearendt** [comment]
Related: https://github.com/rstudio/rstudio-docker-products/issues/64

**Comment by slopp** [comment]
I think the more correct thing to do is just add a new version of R / Py

**Comment by colearendt** [comment]
Closing since this is pretty old. We ended up adding R/Python versions, tracking them in NEWS.md, and trying to get them in sync across the different images. (Some old versions were replaced or removed)

**Pull request closed without merging**
