### PR TITLE
Bump Workbench to CB version 2023.03.1

### PR DESCRIPTION
**Pull request by zachhannum**

### CODE REVIEW

**Comment by samssann** [comment]
any update when this will be released? looking forward to the newest version which will hopefully solve some kubernetes related problems we have been having (rstudio/launcher#604 and rstudio/launcher#645)

**Comment by tuge98** [comment]
Hopefully this will be released soon!

**Review by ianpittwood — CHANGES_REQUESTED** [review]
LGTM, but I think we missed a few spots:
- `docker-compose.yml` still contains a reference to the previous version tag of the image.
- `NEWS.md` entries should be updated for the projects.
- The `README.md` files in each project have a list of "supported tags" that don't look like they've been updated. I'd appreciate if you could tick those up as well! They're automatically published to Docker Hub in addition to Github so they're a helpful reference for customers.

**Review by colearendt — APPROVED** [review]
LGTM!

**Pull request merged**
