### PR TITLE
change session installation order

### PR DESCRIPTION
**Pull request by colearendt**
Installing Workbench last, so that R and Python versions are the "more immutable" parts of the image

### CODE REVIEW

**Review by cm421 — APPROVED** [review]
LGTM!

**Comment by colearendt** [comment]
One thing we are considering to add here is building FROM our newer `content-base` or `content-pro` images, which will require a bit of change in how we structure our CI, so that these session images can build _after_ those images.

**Review by ianpittwood — APPROVED** [review]
Makes sense to me!

**Comment by colearendt** [comment]
I'm thinking we may use #415 in lieu of this PR - it decouples in the same direction, but into completely different files / docker images.

**Comment by colearendt** [comment]
Closed in favor of #454 (which includes #415)

**Pull request closed without merging**
