### PR TITLE
Bump Connect to version 2024.03.0

### PR DESCRIPTION
**Pull request by plascaray**
This PR was created automatically by the Posit Connect release scripts.

### CODE REVIEW

**Review by marcosnav — APPROVED** [review]

**Review by dbkegley — APPROVED** [review]

**Review by aronatkins — CHANGES_REQUESTED** [review]
Update Quarto version before merge.

**Review by aronatkins — APPROVED** [review]
Updated products to use Quarto 1.4. Content images left using old Quarto versions. CC @dbkegley

**Review by dbkegley — APPROVED** [review]

**Comment by dbkegley** [comment]
I don't think this is ever going to pass CI so we can't merge this as-is with the quarto version bump.

https://github.com/rstudio/rstudio-docker-products/blob/73939c2d83a7beb423a6b04f5ed1a5a74f30ae03/connect/Dockerfile.ubuntu2204#L7

<https://github.com/rstudio/rstudio-docker-products/actions/runs/8471492766/job/23211566915?pr=712#step:8:2414>

```
/usr/bin/docker buildx build --build-arg RSC_VERSION=2024.04.0-dev+1-g1616bf165b --build-arg R_VERSION=4.2.3 --build-arg R_VERSION_ALT=4.1.3 --build-arg PYTHON_VERSION=3.9.17 --build-arg PYTHON_VERSION_ALT=3.8.17 --build-arg PYTHON_VERSION_JUPYTER=3.8.17 --build-arg QUARTO_VERSION=1.4.552 --build-arg DRIVERS_VERSION=2024.03.0 --build-arg SRC_IMAGE_NAME=product-base-pro-dev --build-arg RSW_DOWNLOAD_URL=https://s3.amazonaws.com/rstudio-ide-build/server/jammy/amd64 --build-arg RSPM_DOWNLOAD_URL=https://cdn.rstudio.com/package-manager/deb/amd64 --file ./connect/Dockerfile.ubuntu2204 --iidfile /home/runner/work/_temp/docker-actions-toolkit-Q0cuk9/iidfile --tag rstudio/rstudio-connect-preview:ubuntu2204-2024.04.0-dev-1-g1616bf165b --tag rstudio/rstudio-connect-preview:ubuntu2204-2024.04.0 --tag rstudio/rstudio-connect-preview:ubuntu2204-daily --tag ghcr.io/rstudio/rstudio-connect-preview:ubuntu2204-2024.04.0-dev-1-g1616bf165b --tag ghcr.io/rstudio/rstudio-connect-preview:ubuntu2204-2024.04.0 --tag ghcr.io/rstudio/rstudio-connect-preview:ubuntu2204-daily --tag rstudio/rstudio-connect-preview:jammy-2024.04.0-dev-1-g1616bf165b --tag rstudio/rstudio-connect-preview:jammy-2024.04.0 --tag rstudio/rstudio-connect-preview:jammy-daily --tag ghcr.io/rstudio/rstudio-connect-preview:jammy-2024.04.0-dev-1-g1616bf165b --tag ghcr.io/rstudio/rstudio-connect-preview:jammy-2024.04.0 --tag ghcr.io/rstudio/rstudio-connect-preview:jammy-daily --load --metadata-file /home/runner/work/_temp/docker-actions-toolkit-Q0cuk9/metadata-file ./connect
```

We are building from the base pro image but that image has not been updated with the new quarto version:

```
time="2024-03-28T17:55:32.045Z" level=warning msg="Warning: Could not detect Quarto at /opt/quarto/1.4.552/bin/quarto: Could not run Quarto as rstudio-connect; exit status 1; received output: '2024-03-28T17:55:32.045113Z [rsandbox] ERROR system error 2 (No such file or directory); OCCURRED AT int main(int, char* const*) src/cpp/server/sandbox/SandboxMain.cpp:411; LOGGED FROM: int main(int, char* const*) src/cpp/server/sandbox/SandboxMain.cpp:412'"
time="2024-03-28T17:55:32.045Z" level=fatal msg="Error: Unable to configure execution environments: unable to initialize local environment: Unable to use Quarto on this system: Update or remove the configured Quarto installation(s)"
```

```bash
david@Davids-MacBook-Pro:connect [main] » docker run ghcr.io/rstudio/product-base-pro-dev:ubuntu2204-r4.2.3_4.1.3-py3.9.17_3.8.17 ls -al /opt/quarto
total 12
drwxr-xr-x 3 root root 4096 Mar 22 16:19 .
drwxr-xr-x 1 root root 4096 Mar 22 16:25 ..
drwxr-xr-x 4 root root 4096 Mar 22 16:19 1.3.340
```

cc @ianpittwood @bschwedler

**Review by dbkegley — CHANGES_REQUESTED** [review]
We'll need to fix CI before this can merge. The base images don't have the correct quarto version

**Review by dbkegley — APPROVED** [review]

**Review by aronatkins — APPROVED** [review]

**Pull request merged**
